package com.pm.sharedlib.runtime;

public enum OutboundErrorCode {
    ENDPOINT_NOT_REGISTERED,
    CONFIG_MISSING,
    CONFIG_DISABLED,
    CONFIG_INACTIVE,
    PROTOCOL_MISMATCH,
    METHOD_MISMATCH,
    DESTINATION_URL_MISMATCH,
    TOPIC_MISMATCH,
    RETRY_EXHAUSTED,
    PUBLISH_FAILED,
    BROKER_UNAVAILABLE,
    PRODUCER_EXCEPTION,
    SERIALIZATION_ERROR,
    TIMEOUT_EXCEEDED,
    INVOCATION_FAILED
}
