spring.application.name=be

# postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/shared-lib
spring.datasource.username=admin
spring.datasource.password=123456
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect.jdbc.timezone=Asia/Ho_Chi_Minh