export const ROUTES = {
  CLIENTS: 'clients',
  SHARED_APIS: 'sharedApis',
  CLIENT_APIS: 'clientApis',
  DEFAULT_CONFIGS: 'defaultConfigs',
  ACCESS_POLICIES: 'accessPolicies',
};

export const CLIENT_STATUSES = ['ACTIVE', 'INACTIVE', 'REVOKED'];

export const SYNC_STATUSES = ['ACTIVE', 'STALE'];

export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];

export const CLIENT_API_PROTOCOLS = ['HTTP', 'HTTP/1.1', 'HTTP/2', 'gRPC', 'MQ'];

export const APPLY_MODES = ['NEW_ONLY', 'APPLY_TO_EXISTING', 'FORCE_APPLY_ALL'];

export const API_CONFIG_TYPES = ['EXPOSED', 'CLIENT'];

export const DEFAULT_LIMIT_FORM = {
  maxRequests: '',
  throttleWindowSec: '',
  maxRequestKb: '',
  maxResponseKb: '',
  latencyThresholdMs: '',
  timeoutMs: '',
  logRetentionDays: '',
  maxRetries: '',
  retryDelayMs: '',
  failureAction: '',
  notificationRuleId: '',
};

export const SAMPLE_APIS = [
  {
    id: 'sample-1',
    name: 'GetOrderDetails',
    microServiceId: 'svc-order',
    microServiceName: 'order-service',
    method: 'GET',
    path: '/api/v1/orders/{orderId}',
    protocol: 'HTTP/1.1',
    enabled: true,
    useDefaultConfig: true,
    syncStatus: 'ACTIVE',
    lastSyncedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    maxRequests: 1000,
    throttleWindowSec: 60,
    maxRequestKb: 1024,
    maxResponseKb: 2048,
    latencyThresholdMs: 250,
    timeoutMs: 15000,
    logRetentionDays: 30,
  },
  {
    id: 'sample-2',
    name: 'ProcessPayment',
    microServiceId: 'svc-payment',
    microServiceName: 'payment-service',
    method: 'POST',
    path: '/v2/transactions/process',
    protocol: 'gRPC',
    enabled: true,
    useDefaultConfig: false,
    syncStatus: 'STALE',
    lastSyncedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    maxRequests: 5000,
    throttleWindowSec: 10,
    maxRequestKb: 2048,
    maxResponseKb: 2048,
    latencyThresholdMs: 50,
    timeoutMs: 2000,
    logRetentionDays: 90,
  },
  {
    id: 'sample-3',
    name: 'LegacyAuthToken',
    microServiceId: 'svc-auth',
    microServiceName: 'user-auth-service',
    method: 'DELETE',
    path: '/auth/legacy/session',
    protocol: 'HTTP/1.1',
    enabled: false,
    useDefaultConfig: false,
    syncStatus: 'STALE',
    lastSyncedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    maxRequests: 500,
    throttleWindowSec: 1,
    maxRequestKb: 1024,
    maxResponseKb: 1024,
    latencyThresholdMs: 100,
    timeoutMs: 5000,
    logRetentionDays: 7,
  },
  {
    id: 'sample-4',
    name: 'UpdateStockLevel',
    microServiceId: 'svc-inventory',
    microServiceName: 'inventory-service',
    method: 'PUT',
    path: '/v1/stock/batch-update',
    protocol: 'HTTP/1.1',
    enabled: true,
    useDefaultConfig: true,
    syncStatus: 'ACTIVE',
    lastSyncedAt: new Date(Date.now() - 45 * 1000).toISOString(),
    maxRequests: 1200,
    throttleWindowSec: 60,
    maxRequestKb: 2048,
    maxResponseKb: 2048,
    latencyThresholdMs: 300,
    timeoutMs: 15000,
    logRetentionDays: 30,
  },
  {
    id: 'sample-5',
    name: 'BulkRefundOrder',
    microServiceId: 'svc-payment',
    microServiceName: 'payment-service',
    method: 'POST',
    path: '/v2/refunds/bulk',
    protocol: 'HTTP/1.1',
    enabled: false,
    useDefaultConfig: false,
    syncStatus: 'STALE',
    lastSyncedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    maxRequests: 800,
    throttleWindowSec: 60,
    maxRequestKb: 2048,
    maxResponseKb: 2048,
    latencyThresholdMs: 500,
    timeoutMs: 10000,
    logRetentionDays: 30,
  },
];

export const SAMPLE_DEFAULT_CONFIGS = [
  {
    id: 'default-global',
    apiType: 'EXPOSED',
    scope: 'GLOBAL',
    microServiceId: null,
    microServiceName: null,
    enabled: true,
    maxRequests: 1000,
    throttleWindowSec: 60,
    maxRequestKb: 5120,
    maxResponseKb: 5120,
    latencyThresholdMs: 250,
    timeoutMs: 15000,
    logRetentionDays: 30,
    notificationRuleId: null,
    updatedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
  },
  {
    id: 'default-payment',
    apiType: 'EXPOSED',
    scope: 'SERVICE',
    microServiceId: 'svc-payment',
    microServiceName: 'Payment-Gateway-V2',
    enabled: true,
    maxRequests: 5000,
    throttleWindowSec: 10,
    maxRequestKb: 2048,
    maxResponseKb: 2048,
    latencyThresholdMs: 50,
    timeoutMs: 2000,
    logRetentionDays: 90,
    notificationRuleId: null,
    updatedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
  },
  {
    id: 'default-auth',
    apiType: 'CLIENT',
    scope: 'SERVICE',
    microServiceId: 'svc-auth',
    microServiceName: 'User-Auth-Service',
    enabled: false,
    latencyThresholdMs: 100,
    timeoutMs: 5000,
    maxRetries: 1,
    retryDelayMs: 250,
    failureAction: 'SKIP_OPTIONAL_CHECK',
    logRetentionDays: 7,
    notificationRuleId: null,
    updatedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
  },
];

export const SAMPLE_CLIENT_APIS = [
  {
    id: 'client-api-sample-1',
    microServiceId: 'svc-order',
    microServiceName: 'order-service',
    clientId: null,
    name: 'PaymentAuthorizeClient',
    destinationUrl: 'http://payment-service/api/v1/payments/authorize',
    method: 'POST',
    protocol: 'HTTP/1.1',
    latencyThresholdMs: 300,
    timeoutMs: 5000,
    maxRetries: 3,
    retryDelayMs: 1000,
    failureAction: 'LOG_AND_FAIL',
    logRetentionDays: 30,
    notificationRuleId: null,
    useDefaultConfig: true,
    enabled: true,
    syncStatus: 'ACTIVE',
    lastSyncedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'client-api-sample-2',
    microServiceId: 'svc-inventory',
    microServiceName: 'inventory-service',
    clientId: null,
    name: 'OrderStatusLookup',
    destinationUrl: 'http://order-service/api/v1/orders/{orderId}',
    method: 'GET',
    protocol: 'HTTP/2',
    latencyThresholdMs: 150,
    timeoutMs: 3000,
    maxRetries: 2,
    retryDelayMs: 500,
    failureAction: 'RETRY_THEN_ALERT',
    logRetentionDays: 14,
    notificationRuleId: null,
    useDefaultConfig: false,
    enabled: true,
    syncStatus: 'ACTIVE',
    lastSyncedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: 'client-api-sample-3',
    microServiceId: 'svc-auth',
    microServiceName: 'user-auth-service',
    clientId: null,
    name: 'LegacyRiskScoreClient',
    destinationUrl: 'grpc://risk-service/RiskScore/Get',
    method: 'POST',
    protocol: 'gRPC',
    latencyThresholdMs: 80,
    timeoutMs: 2000,
    maxRetries: 1,
    retryDelayMs: 250,
    failureAction: 'SKIP_OPTIONAL_CHECK',
    logRetentionDays: 7,
    notificationRuleId: null,
    useDefaultConfig: true,
    enabled: false,
    syncStatus: 'STALE',
    lastSyncedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
